﻿CREATE DATABASE QUANLYSUKIEN
USE QUANLYSUKIEN

-- Bảng người dùng
CREATE TABLE NGUOIDUNG
(
	MAND CHAR(5) CONSTRAINT PK_ND PRIMARY KEY,
	HOTEN NVARCHAR(30) NOT NULL,
	GIOITINH NVARCHAR(4) NOT NULL, CHECK (GIOITINH IN ('Nam', N'Nữ')),
	MAKHOA CHAR(6) CONSTRAINT FK_ND_KHOA FOREIGN KEY REFERENCES KHOA(MAKHOA),
	PASSWORDUSER VARCHAR(MAX),
	EMAIL VARCHAR(MAX),
	SDT VARCHAR(11) NOT NULL, CHECK(LEN(SDT) BETWEEN 9 AND 11),
	MASVGV VARCHAR(10),
	ROLEUSER INT,
	IMAGEUSER VARBINARY(MAX) NOT NULL
)

-- Bảng khoa
CREATE TABLE KHOA 
(
	MAKHOA CHAR(6) CONSTRAINT PK_KHOA PRIMARY KEY,
	TENKHOA NVARCHAR(MAX) NOT NULL
)

-- Bảng sự kiện
CREATE TABLE SUKIEN 
(
	MASK CHAR(5) CONSTRAINT PK_SK PRIMARY KEY,
	TENSK NVARCHAR(MAX) NOT NULL,
	DVTC CHAR(6) NOT NULL CONSTRAINT FK_SUKIEN_KHOA FOREIGN KEY REFERENCES KHOA(MAKHOA),
	THELOAI NVARCHAR(MAX) NOT NULL,
	MOTA NVARCHAR(MAX) NOT NULL,
	MANDB CHAR(5) NOT NULL CONSTRAINT FK_MANDB_ND FOREIGN KEY REFERENCES NGUOIDUNG(MAND),
	SOLUONGTHAMGIA INT NOT NULL,
	NGAYMODANGKY SMALLDATETIME NOT NULL,
	NGAYDONGDANGKY SMALLDATETIME NOT NULL,
	VENUE NVARCHAR(MAX),
	PHANTHUONG NVARCHAR(MAX),
	NGAYBATDAU SMALLDATETIME NOT NULL,
	NGAYKETTHUC SMALLDATETIME NOT NULL,
	IMAGEEVENT VARBINARY(MAX),
	NHATAITRO NVARCHAR(MAX),
	DUYET INT 
)

-- Bảng đăng ký sự kiện
CREATE TABLE DANGKYSUKIEN 
(
	MADK CHAR(5) CONSTRAINT PK_DKSK PRIMARY KEY,
	MASK CHAR(5) CONSTRAINT FK_DKSK_SK FOREIGN KEY REFERENCES SUKIEN(MASK),
	MAND CHAR(5) CONSTRAINT FK_NDDK_ND FOREIGN KEY REFERENCES NGUOIDUNG(MAND),
	THOIGIANDANGKY SMALLDATETIME NOT NULL,
	XACNHANTHAMGIA CHAR(6)
)
ALTER TABLE DANGKYSUKIEN ADD CONSTRAINT CK_XACNHANTHAMGIA CHECK (XACNHANTHAMGIA IN (N'Có', N'Không'));

-- Data bảng khoa
INSERT INTO KHOA VALUES ('KH0001', N'Công Nghệ Phần Mềm')
INSERT INTO KHOA VALUES ('KH0002', N'Hệ Thống Thông Tin')
INSERT INTO KHOA VALUES ('KH0003', N'Khoa Học Máy Tính')
INSERT INTO KHOA VALUES ('KH0004', N'Kỹ Thuật Máy Tính')
INSERT INTO KHOA VALUES ('KH0005', N'Mạng Máy Tính Và Truyền Thông')
INSERT INTO KHOA VALUES ('KH0006', N'Khoa Học Và Kỹ Thuật Thông Tin')
	
				